Binary_Classification
- German credit data에서 Credit risk가 있는 고객과 없는 고객을 분류해보자!

## 1. Import Required Libraries

In [129]:
import pandas as pd
import matplotlib.pylab as plt
import numpy as np
%matplotlib inline
import sklearn.metrics as metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import normalize
import torch
import torch.nn as nn
from torch.autograd import Variable
import torch.optim as optim
import torch.nn.init as init
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

## 2. Generate Data

### Attribute Information

__Check__:
status of existing checking account


A11 : ... < 0 DM

A12 : 0 <= ... < 200 DM 

A13 : ... >= 200 DM / salary assignments for at least 1 year 

A14 : no checking account 

&nbsp;
    
__Duration__:
Duration in month

&nbsp;

__History__:
credit history

A30 : no credits taken/ all credits paid back duly 

A31 : all credits at this bank paid back duly 

A32 : existing credits paid back duly till now 

A33 : delay in paying off in the past 

A34 : critical account/ other credits existing (not at this bank) 

&nbsp;

__Purpose__:
Purpose

A40 : car (new) 

A41 : car (used)

A42 : furniture/equipment 

A43 : radio/television 

A44 : domestic appliances 

A45 : repairs 

A46 : education 

A47 : (vacation - does not exist?)

A48 : retraining 

A49 : business 

A410 : others 

&nbsp;

__Credit__:
Credit amount

&nbsp;

__Savings__:
Savings account/bonds

A61 : ... < 100 DM 

A62 : 100 <= ... < 500 DM

A63 : 500 <= ... < 1000 DM 

A64 : .. >= 1000 DM 

A65 : unknown/ no savings account 

&nbsp;

__Employment__:
Present emplyment since

A71 : unemployed 

A72 : ... < 1 year

A73 : 1 <= ... < 4 years 

A74 : 4 <= ... < 7 years 

A75 : .. >= 7 years 

&nbsp;

__Installment__:
Installment rate in percentage of disposable income 

&nbsp;

__Personal__:
Personal status and sex

A91 : male : divorced/separated 

A92 : female : divorced/separated/married 

A93 : male : single 

A94 : male : married/widowed 

A95 : female : single

&nbsp;

__Debtors__:
Other debtors / guarantors

A101 : none 

A102 : co-applicant 

A103 : guarantor 

&nbsp;

__Residence__:
Present residence since

&nbsp;

__Property__:
Property

A121 : real estate 

A122 : if not A121 : building society savings agreement/ life insurance 

A123 : if not A121/A122 : car or other, not in attribute 6 

A124 : unknown / no property 

&nbsp;

__Age(Numerical)__:
Age in years

&nbsp;

__Others__:
Other installment plans

A141 : bank 

A142 : stores 

A143 : none 

&nbsp;

__Housing__
Housing

A151 : rent 

A152 : own 

A153 : for free 

&nbsp;

__numcredits__:
Number of existing credits at this bank

&nbsp;

__Job__:
Job

A171 : unemployed/ unskilled - non-resident 

A172 : unskilled - resident 

A173 : skilled employee / official 

A174 : management/ self-employed/ 

highly qualified employee/ officer 

&nbsp;

__Residpeople__:
Number of people being liable to provide maintenance for

&nbsp;

__Telephone__:
Telephone

A191 : none 

A192 : yes, registered under the customers name 

&nbsp;

__Foreign__:
Foreign worker

A201 : yes 

A202 : no 

&nbsp;

__y__: 
Credit Risks

1 : Yes

2: No

In [23]:
german = pd.read_csv("german.csv",index_col= 0) # index_col=0 해두면 Unnamed: 0 사라짐
print(german.shape) ## 1000개의 데이터 20개의 feature

(1000, 21)

In [27]:
german.iloc[0,:] ## Qualitative data가 많아서 다 dummy화 시켜준다.

check           A11
duration          6
history         A34
purpose         A43
credit         1169
savings         A65
employment      A75
installment       4
personal        A93
debtors        A101
residence         4
property       A121
age              67
others         A143
housing        A152
numcredits        2
job            A173
residpeople       1
telephone      A192
foreign        A201
y                 1
Name: 1, dtype: object

In [31]:
german.isnull().sum() ## 결측치 확인

check          0
duration       0
history        0
purpose        0
credit         0
savings        0
employment     0
installment    0
personal       0
debtors        0
residence      0
property       0
age            0
others         0
housing        0
numcredits     0
job            0
residpeople    0
telephone      0
foreign        0
y              0
dtype: int64

In [29]:
german_categorized = pd.get_dummies(german)
german_categorized.head()

,duration,credit,installment,residence,age,numcredits,residpeople,y,check_A11,check_A12,...,housing_A152,housing_A153,job_A171,job_A172,job_A173,job_A174,telephone_A191,telephone_A192,foreign_A201,foreign_A202
1,6,1169,4,4,67,2,1,1,1,0,...,1,0,0,0,1,0,0,1,1,0
2,48,5951,2,2,22,1,1,0,0,1,...,1,0,0,0,1,0,1,0,1,0
3,12,2096,2,3,49,1,2,1,0,0,...,1,0,0,1,0,0,1,0,1,0
4,42,7882,2,4,45,1,2,1,1,0,...,0,1,0,0,1,0,1,0,1,0
5,24,4870,3,4,53,2,2,0,1,0,...,0,1,0,0,1,0,1,0,1,0

In [236]:
## Testset을 100개 남겨놓고 나머지 900개의 dataset을 train valid set으로 남겨둡니다. 

data_X = german_categorized.drop(['y'], axis=1)
data_y = german_categorized['y']

test_X = data_X.iloc[900:,:]
test_y = data_y.iloc[900:]

train_data_X = data_X.iloc[:900,:]
train_data_y = data_y.iloc[:900]

In [368]:
train_X,valid_X,train_y,valid_y = train_test_split(train_data_X,train_data_y,test_size=0.15,random_state=0)

In [369]:
# train, valid dataset을 출력할 수 있는 class를 만듭니다.
class MakeData(Dataset):
    
    def __init__(self, X_data, y_data):
        self.X_data = X_data
        self.y_data = y_data
        
    def __getitem__(self, index):
        return self.X_data[index], self.y_data[index]
        
    def __len__ (self):
        return len(self.X_data)

In [370]:
train_X.shape

(765, 61)

In [371]:
# normalize까지만 전처리를 해보겠습니다.
train_data = MakeData(np.array(normalize(train_X)), np.array(train_y))
test_data = MakeData(np.array(normalize(valid_X)), np.array(valid_y))

In [372]:
train_data.__getitem__(0)

(array([6.38706501e-03, 9.99841802e-01, 1.06451084e-03, 1.06451084e-03,
        1.64999179e-02, 2.66127709e-04, 2.66127709e-04, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 2.66127709e-04, 0.00000000e+00,
        0.00000000e+00, 2.66127709e-04, 0.00000000e+00, 0.00000000e+00,
        2.66127709e-04, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 2.66127709e-04, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.66127709e-04,
        0.00000000e+00, 2.66127709e-04, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 2.66127709e-04, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 2.66127709e-04, 0.00000000e+00,
        0.00000000e+00, 2.66127709e-04, 0.00000000e+00, 0.00000000e+00,
        2.66127709e-04, 0.00000000e+00, 0.00000000e+00, 2.66127709e-04,
        0.00000000e+00, 0.00000000e+00, 2.66127709e-04, 2.66127709e-04,
        0.00000000e+00]), 1)

## 3. Model & Optimizer

In [373]:
class Binary_Classification(nn.Module):
    def __init__(self):
        super(Binary_Classification, self).__init__()
       
        self.Layer_1 = nn.Linear(61, 30) # Layer를 2개 쌓았다.
        self.Layer_2 = nn.Linear(30, 6)

        
        self.dropout = nn.Dropout(0.5)
        self.sigmoid = nn.Sigmoid()
        self.out = nn.Linear(6,1)
        
        
    def forward(self, inputs):
        x = self.Layer_1(inputs)
        x = self.sigmoid(x)
        x = self.dropout(x)
        
        x = self.Layer_2(x)
        x = self.sigmoid(x)
        x = self.dropout(x)
        
        
        x = self.out(x)
        x = self.sigmoid(x)
        return x 
        # cutoff 가 0.5이면 round(x)를 반환하면 됩니다
    
    def predict(self,test_inputs):
        # test에서는 dropout하면 안됩니다. 
        
        x = self.Layer_1(test_inputs)
        x = self.sigmoid(x)
        
        x = self.Layer_2(x)
        x = self.sigmoid(x)
        
        x= self.out(x)
        x = self.sigmoid(x)
        
        return x

In [374]:
EPOCHS = 5000
BATCH_SIZE = 64

model = Binary_Classification()

# Loss 는 binary cross entropy
criterion = nn.BCELoss()

train_loader = DataLoader(dataset = train_data, batch_size=BATCH_SIZE, shuffle = True)
optimizer = optim.Adam(model.parameters(),lr = 0.01)
for epoch in range(EPOCHS):
    for X_batch, y_batch in train_loader:
        inputs = Variable(torch.Tensor(X_batch.float()))
        targets = Variable(torch.Tensor(y_batch.float())).unsqueeze(1)
        
        model.zero_grad()
        
        y_pred = model(inputs)
        
        loss = criterion(y_pred, targets)
        loss.backward()
        
        optimizer.step()
        
    if epoch % 1000 ==0:
        print(loss)

tensor(0.6899, grad_fn=<BinaryCrossEntropyBackward>)
tensor(0.6123, grad_fn=<BinaryCrossEntropyBackward>)
tensor(0.6710, grad_fn=<BinaryCrossEntropyBackward>)
tensor(0.5397, grad_fn=<BinaryCrossEntropyBackward>)
tensor(0.4688, grad_fn=<BinaryCrossEntropyBackward>)

## 4. Check Trained Parameters
- validset이용해서 적절한 cutoff찾는다
- 이를 다시 testset에 적용

In [375]:
y_pred = model.predict(torch.Tensor(normalize(valid_X)))

In [376]:
def Binary(x,cutoff):
    if x < cutoff:
        return 0
    else:
        return 1

In [381]:
f1_score = []
for i in [0.6,0.61,0.62,0.63,0.64,0.65,0.66,0.67,0.68,0.69,0.7,0.71,0.72,0.73,0.74,0.75]:
    Binary_output = [Binary(x,i) for x in y_pred]
    Binary_output = np.array(Binary_output) 
    f1 = metrics.f1_score(valid_y, Binary_output)
    f1_score.append(f1)

In [382]:
f1_score

[0.8372093023255814,
 0.8372093023255814,
 0.8317757009345794,
 0.8396226415094339,
 0.838095238095238,
 0.8461538461538463,
 0.8275862068965518,
 0.8316831683168318,
 0.835820895522388,
 0.8241206030150754,
 0.8186528497409326,
 0.8167539267015708,
 0.8042328042328042,
 0.8043478260869564,
 0.7840909090909091,
 0.7771428571428571]

In [388]:
## cutoff = 0.63에서 f1_score가 0.8435으로 가장 높게 나왔다. 

y_pred = model.predict(torch.Tensor(normalize(test_X)))
y_pred = [Binary(x,0.63) for x in y_pred] # cutoff 0.63으로 설정
test_y = np.array(test_y)
f1 = metrics.f1_score(y_pred, test_y)
accuracy = metrics.accuracy_score(y_pred, test_y)

In [389]:
print(f1)
print(accuracy)

0.8157894736842106
0.72